version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
  nginx:
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

volumes:
  grafana_data: {}
